Adding My Project
fossasia/Flask_Simple_Form pull request #17
Opened 2017-12-23 13:04 UTC by niteshkumarniranjan

2017-12-25 08:15 UTC, niteshkumarniranjan commented
@poush Please Review this.

2017-12-25 08:51 UTC, 0x48piraj requested changes
**Randomly, It gives me :**

![image](https://user-images.githubusercontent.com/5800726/34336589-6c11361e-e97e-11e7-8303-46daede46409.png)

> It's leaking, I think. Same set of `string` gives mixed responses.

2017-12-25 08:57 UTC, 0x48piraj commented
**I made an `.gif`of the bug. Hope it helps!**

![bug_flask.gif](https://files.gitter.im/0x48piraj/GiWG/thumb/bug_flask.gif)

2017-12-25 09:32 UTC, niteshkumarniranjan commented
@0x48piraj Check it again.

2017-12-25 09:45 UTC, vaibhavsingh97 requested changes

2017-12-25 09:45 UTC, vaibhavsingh97 commented on niteshkumarniranjan/app.py
> +    form = simple_form()
So If i submit form than, it should promt for user to enter text

2017-12-26 17:40 UTC, niteshkumarniranjan commented
@vaibhavsingh97 Fixed That 
![screenshot 96](https://user-images.githubusercontent.com/20199181/34361645-fac86bc0-ea91-11e7-9419-6d93e8394333.png)

2017-12-26 17:45 UTC, NaviRocker approved these changes
LGTM

2017-12-26 18:30 UTC, 0x48piraj approved these changes
Seems good now :+1: 

Thanks for your patience :heart:

2017-12-27 06:02 UTC, vaibhavsingh97 approved these changes

2017-12-27 06:03 UTC, merged